### PR TITLE
Denoise MNI152NLin6Asym:res-2

### PR DESCRIPTION
**Pull request by tsalo**
Related to #39.

## Changes proposed in this pull request

- Write out denoised MNI152NLin6Asym data. `--output-spaces` still isn't supported.

### CODE REVIEW

**Comment by tsalo** [comment]
New tree:

```
.
├── dataset_description.json
├── logs
│   ├── CITATION.bib
│   ├── CITATION.html
│   ├── CITATION.md
│   └── CITATION.tex
├── sub-01
│   ├── ses-01
│   │   ├── figures
│   │   │   ├── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-about_bold.html
│   │   │   ├── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-aroma_bold.svg
│   │   │   ├── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-metrics_bold.svg
│   │   │   └── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-summary_bold.html
│   │   └── func
│   │       ├── sub-01_ses-01_task-rest_desc-aroma_metrics.json
│   │       ├── sub-01_ses-01_task-rest_desc-aroma_metrics.tsv
│   │       ├── sub-01_ses-01_task-rest_desc-melodic_timeseries.tsv
│   │       ├── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-aggrDenoised_bold.nii
│   │       ├── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-melodic_components.nii.gz
│   │       ├── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-melodic_mixing.tsv
│   │       ├── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-nonaggrDenoised_bold.nii
│   │       └── sub-01_ses-01_task-rest_space-MNI152NLin6Asym_desc-orthaggrDenoised_bold.nii
│   └── ses-02
│       ├── figures
│       │   ├── sub-01_ses-02_task-rest_space-MNI152NLin6Asym_desc-aroma_bold.svg
│       │   └── sub-01_ses-02_task-rest_space-MNI152NLin6Asym_desc-metrics_bold.svg
│       └── func
│           ├── sub-01_ses-02_task-rest_desc-aroma_metrics.json
│           ├── sub-01_ses-02_task-rest_desc-aroma_metrics.tsv
│           ├── sub-01_ses-02_task-rest_desc-melodic_timeseries.tsv
│           ├── sub-01_ses-02_task-rest_space-MNI152NLin6Asym_desc-aggrDenoised_bold.nii
│           ├── sub-01_ses-02_task-rest_space-MNI152NLin6Asym_desc-melodic_components.nii.gz
│           ├── sub-01_ses-02_task-rest_space-MNI152NLin6Asym_desc-melodic_mixing.tsv
│           ├── sub-01_ses-02_task-rest_space-MNI152NLin6Asym_desc-nonaggrDenoised_bold.nii
│           └── sub-01_ses-02_task-rest_space-MNI152NLin6Asym_desc-orthaggrDenoised_bold.nii
├── sub-01_anat.html
├── sub-01_ses-01_func.html
└── sub-01_ses-02_func.html
```

**Comment by tsalo** [comment]
Not sure why there's no res entity or why the files aren't compressed...

**Comment by effigies** [comment]
You probably need to set `compress=True` on the derivativesdatasink.

**Comment by tsalo** [comment]
Thanks!

**Pull request merged**
