### PR TITLE
[DATALAD] Added subdataset

### PR DESCRIPTION
**Pull request by effigies**
Starting adding test data to top-level `tests/`

### CODE REVIEW

**Comment by tsalo** [comment]
I think the "minimal" version needs the boldref-space brain mask: `sub-01/func/sub-01_task-mixedgamblestask_run-[01|02]_desc-brain_mask.nii.gz`, which the "full" version shouldn't have since func-space outputs weren't requested.

**Comment by effigies** [comment]
I don't think the minimal version produces brain masks. I guess that's a bug?

**Comment by tsalo** [comment]
In the fmriprep docs it says that the file is created: https://fmriprep.org/en/stable/outputs.html#functional-derivatives (see the first admonition)

**Comment by tsalo** [comment]
Though I don't know if the mask referenced in the docs is in standard space or not. I could have misread it.

**Pull request merged**
